name: c2b2-hackathon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - affine==2.4.0
    - attrs==25.4.0
    - blinker==1.9.0
    - certifi==2025.10.5
    - click==8.3.0
    - click-plugins==1.1.1.2
    - cligj==0.7.2
    - colorama==0.4.6
    - contourpy==1.3.3
    - cycler==0.12.1
    - Flask==3.1.2
    - fonttools==4.60.1
    - itsdangerous==2.2.0
    - Jinja2==3.1.6
    - joblib==1.5.2
    - kiwisolver==1.4.9
    - MarkupSafe==3.0.3
    - matplotlib==3.10.7
    - numpy==2.3.3
    - packaging==25.0
    - pandas==2.3.3
    - pillow==11.3.0
    - pyparsing==3.2.5
    - pyproj==3.7.2
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - rasterio==1.4.3
    - scikit-learn==1.7.2
    - scipy==1.16.2
    - seaborn==0.13.2
    - six==1.17.0
    - threadpoolctl==3.6.0
    - tzdata==2025.2
    - Werkzeug==3.1.3
    - xgboost==3.0.5
    - plotly==6.3.1